#!/bin/sh

term() {
  FILES=""
  while read file
  do
    FILES="$FILES\n$file"
  done
  f=$(printf "$FILES" | sed 1d)
  echo $f
  export f
  i3-sensible-terminal
}

case "$1" in 
  "o")
    term ;;
  "h")
    notify-send "$(cat ~/.config/sxiv/exec/key-handler)" ;;
esac;

while read file
do
  case "$1" in
    "r")
      echo "$file" ;;
    "t")
      dragon "$file" ;;
    "x")
      trash-put "$file" ;;
    "c")
      xclip -selection clipboard -t image/png -i "$file"; notify-send "copied $file to clipboard" ;;
    "d")
      i3-sensible-terminal -e "lf" "$file" ;;
  esac
done
